version: '3'

services:
    api:
        build: ./api
        working_dir: /usr/src/app
        restart: on-failure
        ports:
            - 3001:8080
        command: ./node_modules/nodemon/bin/nodemon ./main.js
    client:
        build: ./client
        working_dir: /usr/src/app/
        restart: on-failure
        depends_on: 
            - api
        ports:
            - 3000:3000
        command: npm start